spring:
  application:
    name: taskManager
  security:
    user:
      name: ${LOC_NAME}
      password: ${LOC_PASSWORD}
  #  profiles:
#    active: dev

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create

base-url: /api