spring:
  application:
    name: taskManager
#  profiles:
#    active: dev

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
