spring:
  application:
    name: taskManager
  security:
    user:
      name: ${LOC_NAME}
      password: ${LOC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mvc:
    hiddenmethod:
      filter:
        enabled: true

base-url: /api