server:
  error:
    include-stacktrace: on_param
    include-message: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-manager
    username: developer
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: INFO
    web: DEBUG
