version: '3'
services:
  task-manager-db-postgresql:
    image: postgres:14.2-alpine3.15
    environment:
      - POSTGRES_DB=task-manager
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      task-manager-network:

networks:
  task-manager-network:
